// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.sl');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Dodaj komentar";
Blockly.Msg.AUTH = "Prosimo, avtoriziraj to aplikacijo, da boš lahko svoje delo shranil(-a) in delil(-a) z drugimi.";
Blockly.Msg.CHANGE_VALUE_TITLE = "Spremeni vrednost:";
Blockly.Msg.CHAT = "Klepetaj s sodelavcem tako, da tipkaš v to okno!";
Blockly.Msg.CLEAN_UP = "Ponastavi kocke";
Blockly.Msg.CLICK_ADD_TOOLTIP = "Add an element";  // untranslated
Blockly.Msg.CLICK_REMOVE_TOOLTIP = "Remove this element";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Skrči kocke";
Blockly.Msg.COLLAPSE_BLOCK = "Skrči kocko";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "barva 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "barva 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "razmerje";
Blockly.Msg.COLOUR_BLEND_TITLE = "mešanica";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Zmeša dve barvi v danem razmerju (0.0 - 1.0).";
Blockly.Msg.COLOUR_BLEND_TYPEBLOCK = "Blend Colour";  // untranslated
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Izberi barvo s palete.";
Blockly.Msg.COLOUR_PICKER_TYPEBLOCK = "Choose Colour";  // untranslated
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "naključna barva";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Izbere naključno barvo.";
Blockly.Msg.COLOUR_RANDOM_TYPEBLOCK = "Random Colour";  // untranslated
Blockly.Msg.COLOUR_RGB_BLUE = "modra";
Blockly.Msg.COLOUR_RGB_GREEN = "zelena";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "rdeča";
Blockly.Msg.COLOUR_RGB_TITLE = "določena barva";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Ustvari barvo z določeno količino rdeče, zelene in modre. Vse vrednosti morajo biti med 0 in 100.";
Blockly.Msg.COLOUR_RGB_TYPEBLOCK = "Colour with";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_BREAK_TYPEBLOCK = "Break Loop";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_CONTINUE_TYPEBLOCK = "Continue Loop";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "izstopi iz zanke";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "nadaljuj z naslednjo ponovitvijo zanke";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Izstopi iz trenutne zanke.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Preskoči preostanek te zanke in nadaljuje z naslednjo ponovitvijo.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Pozor: To kocko lahko uporabiš samo znotraj zanke.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_KEY_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_KEY_TITLE = "for each key %1 in map %2";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_KEY_TYPEBLOCK = "For Each Key In Map";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "za vsak element %1 v seznamu %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Za vsak element v seznamu, nastavi spremenljivko '%1' na ta element. Pri tem se izvedejo določene kocke.";
Blockly.Msg.CONTROLS_FOREACH_TYPEBLOCK = "For Each Item In List";  // untranslated
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "štej s/z %1 od %2 do %3 s korakom %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Vrednost spremenljivke '%1' se spreminja od začetnega števila do končnega števila, z določenim korakom. Pri tem se izvedejo določene kocke.";
Blockly.Msg.CONTROLS_FOR_TYPEBLOCK = "Count With From To By";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Dodaj pogoj »če« kocki.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Dodaj končni pogoj »če« kocki.";
Blockly.Msg.CONTROLS_IF_ELSE_TYPEBLOCK = "If Else";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSIF_ELSE_TYPEBLOCK = "If Else If Else";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSIF_TYPEBLOCK = "If Else If";  // untranslated
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Dodaj, odstrani ali spremeni vrstni red odsekov za ponovno nastavitev »če« kocke.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "sicer";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "sicer če";
Blockly.Msg.CONTROLS_IF_MSG_IF = "če";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Če je vrednost resnična, izvedi določene kocke.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Če je vrednost resnična, izvedi prvo skupino kock. Sicer izvedi drugo skupino kock.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Če je prva vrednost resnična, izvedi prvo skupino kock. Sicer, če je resnična druga vrednost, izvedi drugo skupino kock.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Če je prva vrednost resnična, izvedi prvo skupino kock. Sicer, če je resnična druga vrednost, izvedi drugo skupino kock. Če nobena izmed vrednosti ni resnična, izvedi zadnjo skupino kock.";
Blockly.Msg.CONTROLS_IF_TYPEBLOCK = "If";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "izvedi";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "ponavljaj %1 krat";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "repeat";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "times";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Kocke se izvedejo večkrat.";
Blockly.Msg.CONTROLS_REPEAT_TYPEBLOCK = "Repeat Times";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ponavljaj dokler";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ponavljaj";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Kocke se izvajajo dokler je vrednost neresnična.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Kocke se izvajajo dokler je vrednost resnična.";
Blockly.Msg.CONTROLS_WHILEUNTIL_UNTIL_TYPEBLOCK = "Repeat Unitl";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_WHILE_TYPEBLOCK = "Repeat While";  // untranslated
Blockly.Msg.DELETE_ALL_BLOCKS = "Izbrišem vseh %1 kock?";
Blockly.Msg.DELETE_BLOCK = "Izbriši kocko";
Blockly.Msg.DELETE_X_BLOCKS = "Izbriši kocke";
Blockly.Msg.DISABLE_BLOCK = "Onemogoči kocko";
Blockly.Msg.DUPLICATE_BLOCK = "Podvoji";
Blockly.Msg.ENABLE_BLOCK = "Omogoči kocko";
Blockly.Msg.EXPAND_ALL = "Razširi kocke";
Blockly.Msg.EXPAND_BLOCK = "Razširi kocko";
Blockly.Msg.EXTERNAL_INPUTS = "Vnosi zunaj";
Blockly.Msg.HELP = "Pomoč";
Blockly.Msg.IMPORT_JAR = "import jar %1 %2 package %3 class %4 method %5 %6";  // untranslated
Blockly.Msg.IMPORT_JAR_GET = "Create 'get %1'";  // untranslated
Blockly.Msg.IMPORT_JAR_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.IMPORT_JAR_TOOLTIP = "Sets this variable to be equal to the input.";  // untranslated
Blockly.Msg.IMPORT_JAR_TYPEBLOCK = "insert python code";  // untranslated
Blockly.Msg.INITIALIZE_GLOBAL_VARIABLE = "Initialize global";  // untranslated
Blockly.Msg.INITIALIZE_LOCAL_VARIABLE = "Initialize local";  // untranslated
Blockly.Msg.INITIALIZE_VARIABLE = "Initialize %1 as %2 with %3";  // untranslated
Blockly.Msg.INLINE_INPUTS = "Vnosi v vrsti";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "ustvari prazen seznam";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Vrne seznam, dolžine 0, ki ne vsebuje nobenih podatkov.";
Blockly.Msg.LISTS_CREATE_EMPTY_TYPEBLOCK = "Create Empty List";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "seznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Doda, odstrani ali spremeni vrstni red elementov tega seznama.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "ustvari seznam s/z";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Doda element seznamu.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Ustvari seznam s poljubnim številom elementov.";
Blockly.Msg.LISTS_CREATE_WITH_TYPEBLOCK = "Create List With";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_FIRST = "prvo mesto";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "mesto št. od konca";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "vrni";
Blockly.Msg.LISTS_GET_INDEX_GET_FIRST_TYPEBLOCK = "Get First Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_FROM_END_TYPEBLOCK = "Get Item From End of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_FROM_START_TYPEBLOCK = "Get Item From Start of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_LAST_TYPEBLOCK = "Get Last Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_RANDOM_TYPEBLOCK = "Get Random Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "odstrani in vrni";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE_FIRST_TYPEBLOCK = "Get and Remove First Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE_FROM_END_TYPEBLOCK = "Get and Remove Item From End of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE_FROM_START_TYPEBLOCK = "Get and Remove Item From Start of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE_LAST_TYPEBLOCK = "Get and Remove Last Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE_RANDOM_TYPEBLOCK = "Get and Remove Random Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_LAST = "zadnje mesto";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "naključno mesto";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "odstrani";
Blockly.Msg.LISTS_GET_INDEX_REMOVE_FIRST_TYPEBLOCK = "Remove First Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_REMOVE_FROM_END_TYPEBLOCK = "Remove Item From End of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_REMOVE_FROM_START_TYPEBLOCK = "Remove Item From Start of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_REMOVE_LAST_TYPEBLOCK = "Remove Last Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_REMOVE_RANDOM_TYPEBLOCK = "Remove Random Item of List";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vrne prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Vrne element na določenem mestu v seznamu. Zadnji element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Vrne element na določenem mestu v seznamu. Prvi element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vrne zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vrne naključni element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Odstrani in vrne prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Odstrani in vrne element na določenem mestu v seznamu. Zadnji element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Odstrani in vrne element na določenem mestu v seznamu. Prvi element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Odstrani in vrne zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Odstrani in vrne naključni element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Odstrani prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Odstrani element na določenem mestu v seznamu. Zadnji element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Odstrani element na določenem mestu v seznamu. Prvi element je št. 1.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Odstrani zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Odstrani naključni element seznama.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "do mesta št. od konca";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "do mesta št.";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "do zadnjega mesta";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "ustvari podseznam od prvega mesta";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "ustvari podseznam od mesta št. od konca";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "ustvari podseznam od mesta št.";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Ustvari nov seznam, kot kopijo določenega dela seznama.";
Blockly.Msg.LISTS_GET_SUBLIST_TYPEBLOCK = "Get Sub-List";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_FIRST = "najdi prvo pojavitev elementa";
Blockly.Msg.LISTS_INDEX_OF_FIRST_TYPEBLOCK = "Find First Occurrence Of Item";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "najdi zadnjo pojavitev elementa";
Blockly.Msg.LISTS_INDEX_OF_LAST_TYPEBLOCK = "Find Last Occurrence Of Item";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Vrne mesto (indeks) prve/zadnje pojavitve elementa v seznamu. Če elementa ne najde, vrne 0.";
Blockly.Msg.LISTS_INLIST = "v seznamu";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prazen";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vrne resnično, če je seznam prazen.";
Blockly.Msg.LISTS_ISEMPTY_TYPEBLOCK = "Is List Empty?";  // untranslated
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "dolžina %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vrne dolžino seznama.";
Blockly.Msg.LISTS_LENGTH_TYPEBLOCK = "Length Of List";  // untranslated
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "ustvari seznam z elementom %1, ki se ponovi %2 krat";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Ustvari seznam z danim elementom, ki se poljubno mnogo krat ponovi.";
Blockly.Msg.LISTS_REPEAT_TYPEBLOCK = "Create List With Repeated Item";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "element";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "vstavi na";
Blockly.Msg.LISTS_SET_INDEX_INSERT_FIRST_TYPEBLOCK = "Insert at Start of List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INSERT_FROM_END_TYPEBLOCK = "Insert at Position from End of List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INSERT_FROM_START_TYPEBLOCK = "Inserts at Position in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INSERT_LAST_TYPEBLOCK = "Append to End of List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INSERT_RANDOM_TYPEBLOCK = "Insert At Random Location in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET = "nastavi na";
Blockly.Msg.LISTS_SET_INDEX_SET_FIRST_TYPEBLOCK = "Set First Item in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET_FROM_END_TYPEBLOCK = "Set Item at Position from End of List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET_FROM_START_TYPEBLOCK = "Set Item at Position in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET_LAST_TYPEBLOCK = "Set Last Item in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET_RANDOM_TYPEBLOCK = "Set a Random Item in List";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Vstavi element na začetek seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Vstavi element na določeno mesto v seznamu. Zadnji element je št. 1.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Vstavi element na določeno mesto v seznamu. Prvi element je št. 1.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Doda element na konec seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Vstavi element na naključno mesto v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Nastavi prvi element seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Nastavi element na določenem mestu v seznamu. Zadnji element je št. 1.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Nastavi element na določenem mestu v seznamu. Prvi element je št. 1.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Nastavi zadnji element seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Nastavi naključni element seznama.";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "ustvari seznam iz besedila";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT_TYPEBLOCK = "Make List From Text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "ustvari besedilo iz seznama";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST_TYPEBLOCK = "Make Text From List";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Združi seznam besedil v eno besedilo, ločeno z ločilom.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Razdruži besedilo v seznam besedil. Za razdruževanje besedila uporabi ločilo.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "z ločilom";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "neresnično";
Blockly.Msg.LOGIC_BOOLEAN_FALSE_TYPEBLOCK = "False";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vrne resnično ali neresnično.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "resnično";
Blockly.Msg.LOGIC_BOOLEAN_TRUE_TYPEBLOCK = "True";  // untranslated
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vrne resnično, če sta vnosa enaka.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Vrne resnično, če je prvi vnos večji od drugega.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Vrne resnično, če je prvi vnos večji ali enak drugemu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Vrne resnično, če je prvi vnos manjši od drugega.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Vrne resnično, če je prvi vnos manjši ali enak drugemu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vrne resnično, če vnosa nista enaka.";
Blockly.Msg.LOGIC_COMPARE_TYPEBLOCK = "Logic Equal";  // untranslated
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "ne %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Vrne resnično, če je vnos neresničen. Vrne neresnično, če je vnos resničen.";
Blockly.Msg.LOGIC_NEGATE_TYPEBLOCK = "not";  // untranslated
Blockly.Msg.LOGIC_NULL = "prazno";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vrne prazno.";
Blockly.Msg.LOGIC_NULL_TYPEBLOCK = "Null";  // untranslated
Blockly.Msg.LOGIC_OPERATION_AND = "in";
Blockly.Msg.LOGIC_OPERATION_AND_TYPEBLOCK = "and";  // untranslated
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "ali";
Blockly.Msg.LOGIC_OPERATION_OR_TYPEBLOCK = "or";  // untranslated
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vrne resnično, če sta oba vnosa resnična.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vrne resnično, če je vsaj eden od vnosov resničen.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "če neresnično";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "če resnično";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Preveri pogoj v »testu«. Če je pogoj resničen, potem vrne vrednost »če resnično«; sicer vrne vrednost »če neresnično«.";
Blockly.Msg.LOGIC_TERNARY_TYPEBLOCK = "Test";  // untranslated
Blockly.Msg.MAPS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Maps#create-empty-Map";  // untranslated
Blockly.Msg.MAPS_CREATE_EMPTY_TITLE = "create empty map";  // untranslated
Blockly.Msg.MAPS_CREATE_EMPTY_TOOLTIP = "Returns a Map, of length 0, containing no data records";  // untranslated
Blockly.Msg.MAPS_CREATE_EMPTY_TYPEBLOCK = "Create Empty Map";  // untranslated
Blockly.Msg.MAPS_CREATE_HELPURL = "https://github.com/google/blockly/wiki/Maps#create-empty-Map";  // untranslated
Blockly.Msg.MAPS_CREATE_TITLE = "map key %1 as %2";  // untranslated
Blockly.Msg.MAPS_CREATE_TOOLTIP = "Returns a Map, of length 0, containing no data records";  // untranslated
Blockly.Msg.MAPS_CREATE_TYPEBLOCK = "Map Key";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_CONTAINER_TITLE_ADD = "Map";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_CONTAINER_TOOLTIP = "Add, remove, or reorder sections to reconfigure this Map block.";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Maps#create-Map-with";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_INPUT_WITH = "create map with";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_ITEM_TOOLTIP = "Add an item to the Map.";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_TOOLTIP = "Create a Map with any number of items.";  // untranslated
Blockly.Msg.MAPS_CREATE_WITH_TYPEBLOCK = "Create Map With";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_FIRST = "first";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_FROM_END = "# from end";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_GET = "get";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_GET_REMOVE = "get and remove";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_GET_REMOVE_TYPEBLOCK = "Get and Remove Item From a Map";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_GET_TYPEBLOCK = "Get Item From a Map";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_LAST = "last";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_REMOVE = "remove";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_REMOVE_TYPEBLOCK = "Remove Item From a Map";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_TOOLTIP_GET = "Returns the item at the specified position in a Map.";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_TOOLTIP_GET_REMOVE = "Removes and returns the item at the specified position in a Map.";  // untranslated
Blockly.Msg.MAPS_GET_INDEX_TOOLTIP_REMOVE = "Removes the item at the specified position in a Map.";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_FIRST = "find first occurrence of item";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_FIRST_TYPEBLOCK = "Find First Occurrence Of Item";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Maps#getting-items-from-a-Map";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_LAST = "find last occurrence of item";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_LAST_TYPEBLOCK = "Find Last Occurrence Of Item";  // untranslated
Blockly.Msg.MAPS_INDEX_OF_TOOLTIP = "Returns the index of the first/last occurrence of the item in the Map. Returns 0 if text is not found.";  // untranslated
Blockly.Msg.MAPS_INMAP = "in map";  // untranslated
Blockly.Msg.MAPS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Maps#is-empty";  // untranslated
Blockly.Msg.MAPS_ISEMPTY_TITLE = "%1 is empty";  // untranslated
Blockly.Msg.MAPS_ISEMPTY_TOOLTIP = "Returns true if the Map is empty.";  // untranslated
Blockly.Msg.MAPS_ISEMPTY_TYPEBLOCK = "Is Map Empty?";  // untranslated
Blockly.Msg.MAPS_KEYS_TITLE = "get keys of %1";  // untranslated
Blockly.Msg.MAPS_KEYS_TYPEBLOCK = "Get Keys of Map";  // untranslated
Blockly.Msg.MAPS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Maps#length-of";  // untranslated
Blockly.Msg.MAPS_LENGTH_TITLE = "size of %1";  // untranslated
Blockly.Msg.MAPS_LENGTH_TOOLTIP = "Returns the number of entries in a Map.";  // untranslated
Blockly.Msg.MAPS_LENGTH_TYPEBLOCK = "Size Of Map";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Maps#in-Map--set";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_INPUT_TO = "as";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_INSERT = "insert at";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_SET = "set";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_TOOLTIP = "Sets the item at the specified position in a Map.";  // untranslated
Blockly.Msg.MAPS_SET_INDEX_TYPEBLOCK = "Set Item at Position in Map";  // untranslated
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_ADD_TYPEBLOCK = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_DIVIDE_TYPEBLOCK = "/";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_MINUS_TYPEBLOCK = "-";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_MULTIPLY_TYPEBLOCK = "*";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_POWER_TYPEBLOCK = "^";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vrne vsoto dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vrne kvocient dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vrne razliko dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vrne zmnožek dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vrne prvo število na potenco drugega števila.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "spremeni %1 za %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Prišteje število k spremenljivki '%1'.";
Blockly.Msg.MATH_CHANGE_TYPEBLOCK = "Change Variable By Amount";  // untranslated
Blockly.Msg.MATH_CONSTANT_E_TYPEBLOCK = "Constant E";  // untranslated
Blockly.Msg.MATH_CONSTANT_GOLDEN_RATIO_TYPEBLOCK = "Constant Golden Ratio (φ)";  // untranslated
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_INFINITY_TYPEBLOCK = "Constant Infinity (∞)";  // untranslated
Blockly.Msg.MATH_CONSTANT_PI_TYPEBLOCK = "Constant PI";  // untranslated
Blockly.Msg.MATH_CONSTANT_SQRT1_2_TYPEBLOCK = "Constant √ 1/2";  // untranslated
Blockly.Msg.MATH_CONSTANT_SQRT2_TYPEBLOCK = "Constant √ 2";  // untranslated
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Vrne eno izmed običajnih konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), ali ∞ (neskončno).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "omeji %1 na najmanj %2 in največ %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Omeji število, da bo med določenima (vključenima) mejama.";
Blockly.Msg.MATH_CONSTRAIN_TYPEBLOCK = "Constrain Number Low High";  // untranslated
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_FORMAT_AS_DECIMAL_TITLE = "format as decimal  number %1 places %2";  // untranslated
Blockly.Msg.MATH_FORMAT_AS_DECIMAL_TOOLTIP = "Format this number";  // untranslated
Blockly.Msg.MATH_FORMAT_AS_DECIMAL_TYPEBLOCK = "Format as Decimal";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je deljivo s/z";
Blockly.Msg.MATH_IS_DIVISIBLE_BY_TYPEBLOCK = "Number Is Divisible By";  // untranslated
Blockly.Msg.MATH_IS_EVEN = "je sodo";
Blockly.Msg.MATH_IS_EVEN_TYPEBLOCK = "Number Is Even";  // untranslated
Blockly.Msg.MATH_IS_NEGATIVE = "je negativno";
Blockly.Msg.MATH_IS_NEGATIVE_TYPEBLOCK = "Number Is Negative";  // untranslated
Blockly.Msg.MATH_IS_ODD = "je liho";
Blockly.Msg.MATH_IS_ODD_TYPEBLOCK = "Number Is Odd";  // untranslated
Blockly.Msg.MATH_IS_POSITIVE = "je pozitivno";
Blockly.Msg.MATH_IS_POSITIVE_TYPEBLOCK = "Number Is Positive";  // untranslated
Blockly.Msg.MATH_IS_PRIME = "je praštevilo";
Blockly.Msg.MATH_IS_PRIME_TYPEBLOCK = "Number Is Prime";  // untranslated
Blockly.Msg.MATH_IS_TOOLTIP = "Preveri, če je število sodo, liho, praštevilo, celo, pozitivno, negativno ali, če je deljivo z določenim številom. Vrne resnično ali neresnično.";
Blockly.Msg.MATH_IS_WHOLE = "je celo";
Blockly.Msg.MATH_IS_WHOLE_TYPEBLOCK = "Number Is Whole";  // untranslated
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "ostanek pri %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Vrne ostanek pri deljenju dveh števil.";
Blockly.Msg.MATH_MODULO_TYPEBLOCK = "Remainder of";  // untranslated
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Število.";
Blockly.Msg.MATH_ONLIST_AVERAGE_TYPEBLOCK = "Average of List";  // untranslated
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_MAX_TYPEBLOCK = "Max of List";  // untranslated
Blockly.Msg.MATH_ONLIST_MEDIAN_TYPEBLOCK = "Median of List";  // untranslated
Blockly.Msg.MATH_ONLIST_MIN_TYPEBLOCK = "Min of List";  // untranslated
Blockly.Msg.MATH_ONLIST_MODE_TYPEBLOCK = "Mode of List";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "povprečje seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "maksimum seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "mediana seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "minimum seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modus seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "naključni element seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standardni odklon seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "vsota seznama";
Blockly.Msg.MATH_ONLIST_RANDOM_TYPEBLOCK = "Random Item of List";  // untranslated
Blockly.Msg.MATH_ONLIST_STD_DEV_TYPEBLOCK = "Standard Deviation of List";  // untranslated
Blockly.Msg.MATH_ONLIST_SUM_TYPEBLOCK = "Sum of List";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vrne povprečje (aritmetično sredino) števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vrne največje število na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vrne mediano števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vrne najmanjše število na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vrne seznam najpogostejšega elementa(-ov) na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vrne naključno število izmed števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vrne standardni odklon seznama.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vrne vsoto vseh števil na seznamu.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "naključni ulomek";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vrne naključni ulomek med (vključno) 0.0 in 1.0 (izključno).";
Blockly.Msg.MATH_RANDOM_FLOAT_TYPEBLOCK = "Random Fraction";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "naključno število med %1 in %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vrne naključno število med dvema določenima mejama, vključno z mejama.";
Blockly.Msg.MATH_RANDOM_INT_TYPEBLOCK = "Random Integer";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokroži";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokroži navzdol";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokroži navzgor";
Blockly.Msg.MATH_ROUND_ROUNDDOWN_TYPEBLOCK = "Round Down";  // untranslated
Blockly.Msg.MATH_ROUND_ROUNDUP_TYPEBLOCK = "Round Up";  // untranslated
Blockly.Msg.MATH_ROUND_ROUND_TYPEBLOCK = "Round";  // untranslated
Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokroži število navzgor ali navzdol.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolutno";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE_TYPEBLOCK = "Absolute Value";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_NEG_TYPEBLOCK = "Negation";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_ROOT = "kvadratni koren";
Blockly.Msg.MATH_SINGLE_OP_ROOT_TYPEBLOCK = "Square Root";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vrne absolutno vrednost števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Vrne e na potenco števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vrne naravni logaritem števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vrne desetiški logaritem števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vrne negacijo števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vrne 10 na potenco števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vrne kvadratni koren števila.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS_TYPEBLOCK = "ACOS";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN_TYPEBLOCK = "ASIN";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN_TYPEBLOCK = "ATAN";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_COS_TYPEBLOCK = "COS";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_SIN_TYPEBLOCK = "SIN";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TAN_TYPEBLOCK = "TAN";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vrne arkus kosinus števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vrne arkus sinus števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vrne arkus tangens števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vrne kosinus kota v stopinjah (ne radianih).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vrne sinus kota v stopinjah (ne radianih).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vrne tangens kota v stopinjah (ne radianih).";
Blockly.Msg.ME = "Jaz";
Blockly.Msg.NEW_SCOPE_VARIABLE = "New Key...";  // untranslated
Blockly.Msg.NEW_SCOPE_VARIABLE_TITLE = "New Key name:";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Nova spremenljivka...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Ime nove spremenljivke:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "dovoli korake";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s/z:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Izvede uporabniško funkcijo '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Izvede uporabniško funkcijo '%1' in uporabi njen izhod.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s/z:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Ustvari '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Opišite funkcijo ...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "nekaj";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "izvedi";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Ustvari funkcijo brez izhoda.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "vrni";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Ustvari funkcijo z izhodom.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Pozor: Ta funkcija ima podvojene parametre.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Označi definicijo funkcije";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Če je vrednost resnična, vrne drugo vrednost.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Pozor: To kocko lahko uporabiš samo znotraj definicije funkcije.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "ime vnosa:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Funkciji doda vnos.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "vnosi";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Doda, odstrani ali spremeni vrstni red vnosov te funkcije.";
Blockly.Msg.PROCEDURES_NEWTYPE = "New Type...";  // untranslated
Blockly.Msg.PROCEDURES_NEWTYPETITLE = "New Type name:";  // untranslated
Blockly.Msg.PROCEDURES_PARAM_NOTYPE = "with %1 %2%3";  // untranslated
Blockly.Msg.PROCEDURES_PARAM_WITH_TYPE = "with %1 as %2%3%4";  // untranslated
Blockly.Msg.REDO = "Redo";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Odstrani komentar";
Blockly.Msg.RENAME_SCOPE_VARIABLE = "Rename Key...";  // untranslated
Blockly.Msg.RENAME_SCOPE_VARIABLE_TITLE = "Rename all '%1' Keys to:";  // untranslated
Blockly.Msg.RENAME_VARIABLE = "Preimenuj spremenljivko...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Preimenuj vse spremenljivke '%1' v:";
Blockly.Msg.SCOPE_VARIABLES_SET = "set %1 : %2 to %3";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "dodaj besedilo";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "k";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Doda besedilo k spremenljivki '%1'.";
Blockly.Msg.TEXT_APPEND_TYPEBLOCK = "Append Text";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_LOWERCASE_TYPBLOCK = "Text to lower case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "v male črke";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "v Velike Začetnice";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "v VELIKE ČRKE";
Blockly.Msg.TEXT_CHANGECASE_TITLECASE_TYPBLOCK = "Text to Title Case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vrne kopijo besedila v drugi obliki.";
Blockly.Msg.TEXT_CHANGECASE_UPPERCASE_TYPBLOCK = "Text to UPPER CASE";  // untranslated
Blockly.Msg.TEXT_CHARAT_FIRST = "vrni prvo črko";
Blockly.Msg.TEXT_CHARAT_FROM_END = "vrni črko št. od konca";
Blockly.Msg.TEXT_CHARAT_FROM_START = "vrni črko št.";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "iz besedila";
Blockly.Msg.TEXT_CHARAT_LAST = "vrni zadnjo črko";
Blockly.Msg.TEXT_CHARAT_RANDOM = "vrni naključno črko";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Vrne črko na določenem mestu v besedilu.";
Blockly.Msg.TEXT_COMMENT_TEXT = "Comment:";  // untranslated
Blockly.Msg.TEXT_COMMENT_TYPEBLOCK = "Comment";  // untranslated
Blockly.Msg.TEXT_CONTAINS_HELPURL = "http://appinventor.mit.edu/explore/ai2/support/blocks/text#contains";  // untranslated
Blockly.Msg.TEXT_CONTAINS_INPUT = "contains text %1 piece %2";  // untranslated
Blockly.Msg.TEXT_CONTAINS_TOOLTIP = "Tests whether the piece is contained in the text.";  // untranslated
Blockly.Msg.TEXT_CONTAINS_TYPEBLOCK = "Text Contains";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Doda element k besedilu.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "združi";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Doda, odstrani ali spremeni vrstni red elementov tega besedila.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "do črke št. od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END_TYPEBLOCK = " To Letter # From End";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "do črke št.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START_TYPEBLOCK = " To Letter #";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "do zadnje črke";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST_TYPEBLOCK = " To Last Letter";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "iz besedila";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "vrni del od prve črke";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST_TYPEBLOCK = "Get Substring From First Letter";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "vrni del od črke št. od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END_TYPEBLOCK = "Get Substring From Letter # From End";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "vrni del od črke št.";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START_TYPEBLOCK = "Get Substring From Letter #";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Vrne določen del besedila.";
Blockly.Msg.TEXT_INDEXOF_FIRST_TYPEBLOCK = "Find First Occurrence of Text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "v besedilu";
Blockly.Msg.TEXT_INDEXOF_LAST_TYPEBLOCK = "Find Last Occurrence of Text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "najdi prvo pojavitev besedila";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "najdi zadnjo pojavitev besedila";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vrne mesto (indeks) prve/zadnje pojavitve drugega besedila v prvem besedilu. Če besedila ne najde, vrne 0.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prazno";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vrne resnično, če je določeno besedilo prazno.";
Blockly.Msg.TEXT_ISEMPTY_TYPEBLOCK = "Text is Empty";  // untranslated
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "ustvari besedilo iz";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Ustvari besedilo tako, da združi poljubno število elementov.";
Blockly.Msg.TEXT_JOIN_TYPEBLOCK = "Create Text With";  // untranslated
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "dolžina %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vrne število črk oz. znakov (vključno s presledki) v določenem besedilu.";
Blockly.Msg.TEXT_LENGTH_TYPEBLOCK = "Length of Text";  // untranslated
Blockly.Msg.TEXT_PRINTF_CREATEWITH = "create text with";  // untranslated
Blockly.Msg.TEXT_PRINTF_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINTF_TITLE = "printf format %1";  // untranslated
Blockly.Msg.TEXT_PRINTF_TOOLTIP = "Printf the specified text, number or other value.";  // untranslated
Blockly.Msg.TEXT_PRINTF_TYPEBLOCK = "Printf Text";  // untranslated
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "izpiši %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Izpiše določeno besedilo, število ali drugo vrednost.";
Blockly.Msg.TEXT_PRINT_TYPEBLOCK = "Print Text";  // untranslated
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_NUMBER_TYPEBLOCK = "Prompt For Number With Message";  // untranslated
Blockly.Msg.TEXT_PROMPT_TEXT_TYPEBLOCK = "Prompt For Text With Message";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Vpraša uporabnika za vnos števila.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Vpraša uporabnika za vnos besedila.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "vprašaj za število s sporočilom";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "vprašaj za besedilo s sporočilom";
Blockly.Msg.TEXT_SPRINTF_CREATEWITH = "create text with";  // untranslated
Blockly.Msg.TEXT_SPRINTF_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_SPRINTF_TITLE = "sprintf format %1";  // untranslated
Blockly.Msg.TEXT_SPRINTF_TOOLTIP = "Sprintf the specified text, number or other value.";  // untranslated
Blockly.Msg.TEXT_SPRINTF_TYPEBLOCK = "Sprintf Text";  // untranslated
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Črka, beseda ali vrstica besedila.";
Blockly.Msg.TEXT_TOOLTIP_TYPE_JAVA = "Insert arbitrary Java code";  // untranslated
Blockly.Msg.TEXT_TOOLTIP_TYPE_PYTHON = "Insert arbitrary Python code";  // untranslated
Blockly.Msg.TEXT_TRIM_BOTH_TYPEBLOCK = "Trim Spaces From Both Sides Of Text";  // untranslated
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_LEFT_TYPEBLOCK = "Trim Spaces From Left Side Of Text";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "odstrani presledke z obeh strani";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "odstrani presledke z leve strani";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "odstrani presledke z desne strani";
Blockly.Msg.TEXT_TRIM_RIGHT_TYPEBLOCK = "Trim Spaces From Right Side Of Text";  // untranslated
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vrne kopijo besedila z odstranjenimi presledki z ene ali obeh strani.";
Blockly.Msg.TEXT_TYPE_JAVA = "insert java code";  // untranslated
Blockly.Msg.TEXT_TYPE_JAVA_TYPEBLOCK = "insert java code";  // untranslated
Blockly.Msg.TEXT_TYPE_PYTHON = "insert python code";  // untranslated
Blockly.Msg.TEXT_TYPE_PYTHON_TYPEBLOCK = "insert python code";  // untranslated
Blockly.Msg.TODAY = "Danes";
Blockly.Msg.UNDO = "Undo";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "element";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Ustvari 'nastavi %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vrne vrednost spremenljivke.";
Blockly.Msg.VARIABLES_SET = "nastavi %1 na %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Ustvari 'vrni %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Nastavi, da je vrednost spremenljivke enaka vnosu.";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MAPS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.MAPS_GET_INDEX_HELPURL = Blockly.Msg.MAPS_INDEX_OF_HELPURL;
Blockly.Msg.MAPS_SET_INDEX_INPUT_IN_MAP = Blockly.Msg.MAPS_INMAP;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.MAPS_GET_INDEX_INPUT_IN_MAP = Blockly.Msg.MAPS_INMAP;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.MAPS_INDEX_OF_INPUT_IN_MAP = Blockly.Msg.MAPS_INMAP;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;